### ISSUE TITLE
поломка в 1.0.8 

### ISSUE THREAD

**Issue by VlasProgulkin** [alliluja/RSL#11]
SQL синтаксис в строках теперь видит, но перестал подсвечивать все остальные строки. Фактически, в любой строке с двойной кавычкой синтаксис не подсвечивается.  При этом перестала работать команда "Developer: Inspect Editor Tokens and Scopes", всплывает надпись "Loading..." и висит до выхода из редактора.
![image](https://user-images.githubusercontent.com/51082910/75555701-c5754500-5a4d-11ea-86ad-27ebab258778.png)

**Comment by alliluja** [comment]
сливаю в мастер
